name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    # 通过矩阵生成前后端的并行job
    strategy:
      matrix:
        service: [frontend, backend]
        include:
          - service: frontend
            context: ./glyphz
          - service: backend
            context: ./glyphz-backend

    steps:

    - name: Check out the new code
      uses: actions/checkout@v4

    - name: Login to the dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    # 根据matrix中的变量来插值
    - name: Build and push ${{ matrix.service }} image
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.context }}/Dockerfile
        platforms: linux/amd64
        push: true
        tags: nonbeing923/glyphz-${{ matrix.service }}:latest