name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out the new code
      uses: actions/checkout@v4

    - name: Login to the dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push frontend image
      uses: docker/build-push-action@v3
      with:
        context: ./glyphz
        file: ./Dockerfile
        platforms: linux/amd64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/githubaction/${{ env.GITHUB_REPOSITORY_NAME_PART }}/frontend:latest